# common_folder: common
# description: "This function does an important job. Yes :doge:"
# owner: The Wicked Froge🐸 Team
# cpu: 0.15
# memory: 0.25
# env_vars:
#   MY_ENV_VAR: "1337"
#   which_env: "p-p-p-production"
# Alternatively, env_vars: {"MY_ENV_VAR": "1337", "which_env": "p-p-p-production"}
# Parameters that are usually not needed to pass (they have good default values):
# function_file: handler.py  # Use case: Just don't...
# function_deploy_timeout: 1500  # Use case: CDF on Azure has slower deployment speed.
# post_deploy_cleanup: false  # Use case: You want to keep the uploaded zipped code files.

description: "Function to deploy rest extractor"
cpu: 0.1
memory: 0.2
env_vars:
 "COGNITE_BASE_URL": "https://greenfield.cognitedata.com"
 "COGNITE_PROJECT": "bootcamp-03-test"
 "COGNITE_TOKEN_URL": "https://login.microsoftonline.com/16e3985b-ebe8-4e24-9da4-933e21a9fc81/oauth2/v2.0/token"
 "COGNITE_CLIENT_ID": "76cbe02f-905b-4ad8-a768-1ad66f105208"